### ISSUE TITLE
DEFECT: No information capture when create button is pressed.

### ISSUE THREAD

**Issue by B2Gdevs** [B2Gdevs/horse-market-react#8]
On the make-listing page the button here below.
![image](https://user-images.githubusercontent.com/25157436/120251890-83d2db80-c248-11eb-9b72-650d637d1f52.png)

does not capture any input information when clicked.
```js
                        <div className="row">
                            <button className={"btn btn-outline-success mx-auto"}>Create</button>
                        </div>

```

There is no onClick method set to capture the information and no form elements in the rest of makelistings.js

**Comment by ahsan44411** [comment]
@B2Gdevs kindly elaborate more on this and please add me in this repo so I can create a new branch

**Comment by B2Gdevs** [comment]
@ahsan44411 No prob, for this there is no information capture.  Like a form submission.  When we hit create we will need to capture the information that was inputted.  Like the images, the age, name, title of post.  Etc.

The information will need to be captured and then stored when checking out.
